### ISSUE TITLE
ReX Design alpha 版本问题汇总

### ISSUE THREAD

**Issue by yibn2008** [alibaba/rex-design#1]
## 文档问题

1. [x] 代码编辑时，希望 Demo 渲染区域高度是稳定的，否则输入时 Demo 的高度会跳动，输入区域会频繁移动，体验很差；
2. [ ] 多端展示，可以在文档的全局提供 PC(L)|Pad(M)|Phone(S) 三种屏幕尺寸切换，其中 PC 展示全组件文档， Pad|Phone 只展示 demo；
3. [ ] 在 PC 模式的 demo 区域中，允许用户快速切换 PC(L)|Pad(M)|Phone(S) 三种模式的展示；
4. [x] 完善「开始使用」的文档页
5. [x] 文档网站的整体风格不够一致，首页 / 设计文档 / 组件文档三者差异较大，需要进行统一
6. [x] 网站 SEO 和搜索优化

## 组件问题

1. [x] Tooltip 的写法希望优化，可以写成`<Tooltip text="我是按钮的提示"><Button>按钮</Button></Tooltip>`，同时 Tooltip 应该是白色背景，一般来说只推荐写文本（但不做强约束）；
2. [x] menu 需要默认支持 icon
2. [x] Toaster 的动效过强，需要更加优雅的动画效果，B 端的动效应该更加轻量、恰到好处，让用户更加专注在目标内容上；
3. [ ] Timeline 组件对于 datetime 应该做自动折叠，即日期和时间支持断行显示：
    ![image](https://user-images.githubusercontent.com/4136679/116558748-58e82580-a932-11eb-8e65-bf5cbcfd6987.png)
4. [x] Button 的 disabled 状态样式过浅，与背景色的对比度太差，现在几乎不可见：
    ![image](https://user-images.githubusercontent.com/4136679/117274157-60a64d80-ae8f-11eb-99ab-8d35624c08d7.png)
5. [ ] Checkbox 无 focus 样式，使用 tab 键切换无效果： 
    ![image](https://user-images.githubusercontent.com/4136679/117274316-8895b100-ae8f-11eb-8108-21a0bffa1d17.png)
6. [x] Group 组件在默认情况下为块级元素，应该为 inline-block 元素（或 inline-flex 元素）
7. [ ] DatePicker 切换月份时  会存在抖动
    ![image](https://user-images.githubusercontent.com/5550931/118238639-586f9300-b4cb-11eb-81ce-17fb2b7311a8.png)

## 其他

1. [x] 支持 AppProvider 进行受限的嵌套

依赖与导出符号收敛

- [x] 移除 d3
- [x] 移除 styled-system，移除 core/src/system 目录
- [x] hooks/providers/stores/utils 中大部分方法是不需要导出的

## 上次未完成的事项

- Tree 的辅助方法
  - [x] TreeDataHelper
  - [x] StrictTreeDataHelper
  - [x] searchTreeByKeyword
- AdaptiveDialog
  - [x] 基本功能
  - [ ] 移动端细节样式优化
- Notification / toast
  - [x] 样式优化
- focus trap for overlay components with a backdrop by default
  - [ ] drawer
  - [ ] dialog
- 弹层方案持续优化
  - 提供完整的弹层能力，提供丰富的弹层类组件
  - 重点关注：弹层在移动端的表现
  - 暂不包含一些细节交互，例如移动端 通知组件上的手势操作
- [ ] 选择器组件优化
  - 重点关注：移动端中选择器的表现，完整的键盘操作
- [ ] 表格组件移动端展现
- [x] 消除所有 TypeScript 类型报错
- [ ] 减少 any 的使用，换成正确的类型；替换不了的地方使用 unknown 代替 any
- [x] utils 方法收敛与整理

**Comment by shinima** [comment]
持续优化事项

- Tree 的辅助方法
  - [x] TreeDataHelper
  - [x] StrictTreeDataHelper
  - [x] searchTreeByKeyword
  - [ ] 完善辅助方法的文档
- AdaptiveDialog
  - [x] 基本功能
  - [ ] 移动端细节样式优化
- Notification / toast
  - [ ] 样式优化
- focus trap for overlay components with a backdrop by default
  - [ ] drawer
  - [ ] dialog
- 弹层方案持续优化
  - 提供完整的弹层能力，提供丰富的弹层类组件
  - 重点关注：弹层在移动端的表现
  - 暂不包含一些细节交互，例如移动端 通知组件上的手势操作
- [ ] 选择器组件优化
  - 重点关注：移动端中选择器的表现，完整的键盘操作
- [ ] 表格组件移动端展现
- [ ] 消除所有 TypeScript 类型报错
- [ ] 减少 any 的使用，换成正确的类型；替换不了的地方使用 unknown 代替 any
- [ ] utils 方法收敛与整理
